[libraries]
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.9.0" }
clikt = { group = "com.github.ajalt.clikt", name = "clikt", version = "5.0.3" }
